### ISSUE TITLE
File Downloader 下载pdf 证书错误

### ISSUE THREAD

**Issue by qyzh153** [hnshhslsh/virtual-judge#9]
2018-12-18 13:58:49 INFO  FileDownloader:34 - https://uva.onlinejudge.org/external/2/272.pdf
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1509)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:439)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:424)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:178)
	at judge.remote.shared.FileDownloader.downLoadFromUrl(FileDownloader.java:60)
	at judge.remote.shared.FileDownloader.downLoadFromUrl(FileDownloader.java:93)
	at judge.remote.provider.uva.UVACrawler.crawl(UVACrawler.java:84)
	at judge.remote.crawler.SyncCrawler.crawl(SyncCrawler.java:22)
	at judge.remote.ProblemInfoUpdateTask.call(ProblemInfoUpdateManager.java:120)
	at judge.remote.ProblemInfoUpdateTask.call(ProblemInfoUpdateManager.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
	at sun.security.validator.Validator.validate(Validator.java:260)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1491)
	... 23 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:146)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:131)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
	... 29 more

**Comment by hnshhslsh** [comment]
uva 把证书换成 Let's Encrypt 的了，老版本的 Java 不认，最简单的方法是更新一下 Java 版本，比如换成 Java 8 的最新版（现在是`Java SE 8u201 / Java SE 8u202`）。如果你用的是 jspstudy 里集成的，可以本地装上最新的，然后让 jspstudy 用本机的 Java。我大概看了一下，修改`JspStudy2016\tomcat\bin\` 文件夹里的这些配置文件应该可行：
- ` catalina.bat`  和 `service.bat` 第 16 行改成 ：
 `set JRE_HOME=<你的JRE路径>`，我电脑上是：
 `set JRE_HOME=C:\Program Files\Java\jre1.8.0_201`
- ` setclasspath.bat`  第 78 行改成 ：
 `set _RUNJAVA="%JRE_HOME%\bin\java.exe"`

`FileDownloader` 是我自己加的，证书检验的逻辑跟项目里原来的代码不一样，直接用的 Java 默认的逻辑。这个类也有一些别的问题，等我有空修复或者重写一下。

**Comment by zhblue** [comment]
还在维护，手动点赞！
